name: Publish package

on:
  release:
    types: [created]

jobs:
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '16.x'

      - name: Configure NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Instal dependencies
        run: npm install

      - name: Configure Node.js Path
        run: npm config set scripts-prepend-node-path true

      - name: Publish to NPM
        run: npm publish --access=public
